import {PROGRAM} from './program.js';
import {CONFIG} from './config.js';
import {LocalStore} from './store.js';
import {Auth,Cloud,Sync} from './cloud.js';
import {DAY_LABELS,TYPE_LABELS,localDay,parseDay,addDays,monday,programWeek,blockForWeek,buildSteps,validSet,formatTime,formatDate,secondsLeft,suggestion,completedSets,workoutVolume,summarizeExercise} from './core.js';

const $=id=>document.getElementById(id),root=$('app'),modalRoot=$('modal-root');
const h=(tag,attrs={},...children)=>{const node=document.createElement(tag);for(const [key,value] of Object.entries(attrs)){if(value==null||value===false)continue;if(key.startsWith('on'))node.addEventListener(key.slice(2).toLowerCase(),value);else if(key==='class')node.className=value;else if(key==='value')node.value=value;else if(key==='checked'||key==='disabled')node[key]=!!value;else node.setAttribute(key,value===true?'':String(value));}for(const child of children.flat(Infinity)){if(child!=null&&child!==false)node.append(child instanceof Node?child:document.createTextNode(String(child)));}return node;};
function brand(){return h('div',{class:'brand'},h('img',{src:'./icons/logo.svg',alt:'LiftPlan',width:148,height:42}));}
function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),use=document.createElementNS('http://www.w3.org/2000/svg','use');svg.classList.add('icon');svg.setAttribute('aria-hidden','true');use.setAttribute('href',`#i-${name}`);svg.append(use);return svg;}
const button=(label,fn,cls='primary',attrs={})=>h('button',{type:'button',class:cls,onclick:fn,...attrs},label);
const row=(...nodes)=>h('div',{class:'row between'},...nodes);
let toastTimeout;function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
const errorMessage=e=>e?.message||'Something went wrong. Please try again.';
function guard(fn){return async(...args)=>{try{await fn(...args);}catch(e){toast(errorMessage(e));console.error(e.name, e.message);}};}
const DAY_TYPE=['rest','upper','lower','rest','push','pull','legs'];
const demo=new URLSearchParams(location.search).get('preview')==='1';
const auth=new Auth();let store,cloud,sync,profiles=[],profile=null,settings={},logs=[],draft=null,view='today',selectedDay=localDay(),selectedWeek=1,expandedDay=null,draftChain=Promise.resolve(),saving=false,wakeLock=null,registration=null,lastSyncRender=0,sessionScope=null,toastFocus=null;
const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('liftplan-v2'):null;

function openModal(title,content,actions=[]){
 closeModal();toastFocus=document.activeElement;
 const sheet=h('section',{class:'modal',role:'dialog','aria-modal':'true','aria-labelledby':'modal-title',tabindex:'-1'},h('div',{class:'modal-handle'}),row(h('h2',{id:'modal-title'},title),button(icon('close'),closeModal,'icon-button',{'aria-label':'Close dialog'})),content,h('div',{class:'actions'},actions));
 const backdrop=h('div',{class:'modal-backdrop',onclick:e=>{if(e.target===backdrop)closeModal();}},sheet);modalRoot.replaceChildren(backdrop);sheet.focus();document.body.classList.add('dialog-open');
 sheet.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();return;}if(e.key!=='Tab')return;const items=[...sheet.querySelectorAll('button,input,select,textarea,a[href],[tabindex="0"]')].filter(x=>!x.disabled);if(!items.length){e.preventDefault();return;}const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
}
function closeModal(){modalRoot.replaceChildren();document.body.classList.remove('dialog-open');toastFocus?.focus();toastFocus=null;}
function confirm(title,message,label,fn){openModal(title,h('p',{},message),[button(label,guard(async()=>{closeModal();await fn();})),button('Keep training',closeModal,'secondary')]);}
function bootError(error){root.replaceChildren(h('main',{class:'welcome error-panel'},brand(),h('h1',{},'Unable to open your training.'),h('p',{},errorMessage(error)),button('Try again',()=>location.reload()),h('p',{class:'tiny'},'Your existing records have not been cleared.')));}

async function initializeScope(scope){
 sessionScope=scope;store=new LocalStore(scope);await store.open();cloud=demo?null:new Cloud(auth);sync=demo?null:new Sync(store,cloud,()=>updateSyncStatus());
 if(sync)await sync.run();
 const existing=await store.records('profile');
 if(!existing.length){await store.put('profile:brody','profile','brody',{name:'Brody',tone:'green'});await store.put('profile:mackenzie','profile','mackenzie',{name:'Mackenzie',tone:'rose'});}
 profiles=(await store.records('profile')).map(r=>({id:r.profile_id,...r.payload}));
 const saved=localStorage.getItem(`liftplan.v2.profile.${scope}`);profile=profiles.find(p=>p.id===saved)||null;
 if(profile)await loadProfile();else renderProfiles();
 if(sync)sync.run();
}
async function loadProfile(){
 const record=await store.get('records',`settings:${profile.id}`);
 if(!record){settings={startDate:monday(),increment:2.5,overrides:{},sound:false};await store.put(`settings:${profile.id}`,'settings',profile.id,settings);}else settings=record.payload;
 logs=(await store.records('workout',profile.id)).map(r=>({id:r.id,...r.payload}));draft=await store.get('drafts',profile.id)||null;
 selectedWeek=programWeek(settings.startDate);selectedDay=localDay();view='today';render();
}
async function refreshData(){if(!store||!profile)return;const record=await store.get('records',`settings:${profile.id}`);if(record)settings=record.payload;logs=(await store.records('workout',profile.id)).map(r=>({id:r.id,...r.payload}));}
function queueSync(){if(!demo&&sync){const current=sync;sync.run().then(async()=>{if(sync!==current||!profile)return;await refreshData();updateSyncStatus();if(!draft&&view!=='saved'&&view!=='settings'&&Date.now()-lastSyncRender>1500){lastSyncRender=Date.now();render();}});}channel?.postMessage({scope:sessionScope});}
function updateSyncStatus(){const label=$('sync-status');if(label){label.replaceChildren(h('span',{class:'status-dot'}),demo?'Preview':sync?.state==='synced'?'Synced':sync?.state==='syncing'?'Syncing':sync?.state==='offline'?'Offline':sync?.state==='conflict'?'Review changes':'Saved here');label.className=`pill status-${sync?.state||'idle'}`;}const detailed=$('sync-detail');if(detailed)detailed.textContent=demo?'Preview data stays separate from your account.':sync?.message||'Changes are saved on this device.';}
function showSyncInfo(){openModal(demo?'Preview mode':'Your data',h('div',{class:'stack'},h('p',{},demo?'This is a separate preview. It does not sign in or change your live profiles.':sync?.message||'Changes are saved on this device.'),sync?.error?h('p',{class:'tiny'},sync.error):null),[button(demo?'Close':'Retry sync',guard(async()=>{closeModal();if(sync){await sync.run();await refreshData();render();}})),button('Review saved changes',()=>{closeModal();view='settings';render();},'secondary')]);}

function renderWelcome(mode='signin'){
 profile=null;const error=h('p',{class:'form-error',role:'alert'}),email=h('input',{type:'email',name:'email',autocomplete:'username',required:true,placeholder:'you@example.com','aria-label':'Email address'}),password=h('input',{type:'password',name:'password',autocomplete:mode==='signup'?'new-password':'current-password',required:true,minlength:mode==='signup'?'8':'1',placeholder:'Password','aria-label':'Password'}),submit=button(mode==='signup'?'Create shared account':'Sign in',()=>{},'primary',{type:'submit'});
 const form=h('form',{onsubmit:async e=>{e.preventDefault();error.textContent='';submit.disabled=true;try{if(mode==='signup'){const session=await auth.signUp(email.value.trim(),password.value);if(!session){error.textContent='Check your email to confirm your account, then sign in.';submit.disabled=false;return;}}else await auth.signIn(email.value.trim(),password.value);password.value='';await initializeScope(auth.session().user.id);}catch(e){error.textContent=errorMessage(e);submit.disabled=false;}}},h('div',{class:'field'},h('label',{},'Email'),email),h('div',{class:'field'},h('label',{},'Password'),password),error,submit);
 root.replaceChildren(h('main',{class:'welcome'},brand(),h('div',{class:'eyebrow accent'},'YOUR ESSENTIALS COMPANION'),h('h1',{},'Less friction.',h('br'),'More lifting.'),h('p',{},'Five focused training days. A clear next set. Your progress, wherever you train.'),h('div',{class:'features'},h('span',{class:'pill'},'Works offline'),h('span',{class:'pill'},'Resumes your workout'),h('span',{class:'pill'},'Two profiles')),form,button(mode==='signup'?'Already have an account? Sign in':'First time? Create your shared account',()=>renderWelcome(mode==='signup'?'signin':'signup'),'text-button'),h('p',{class:'footer-note'},'Use the same account on both iPhones, then choose your profile.')));
}
function renderProfiles(){profile=null;root.replaceChildren(h('main',{class:'welcome'},demo?h('div',{class:'pill'},'PRIVATE PREVIEW'):null,brand(),h('div',{class:'eyebrow accent'},'ONE PLAN. YOUR OWN PROGRESS.'),h('h1',{},'Who’s',h('br'),'training?'),h('p',{},'Separate workouts. Separate progress. A little shared motivation.'),h('div',{class:'profile-grid'},profiles.map(p=>button([h('div',{class:`avatar ${p.tone==='rose'?'rose':''}`},p.name.slice(0,1).toUpperCase()),h('span',{},p.name)],guard(async()=>{profile=p;localStorage.setItem(`liftplan.v2.profile.${sessionScope}`,p.id);await loadProfile();}),'profile-choice'))),h('p',{class:'footer-note'},'Your profile is remembered on this iPhone.'),!demo?button('Sign out',guard(signOut),'text-button'):null));}
async function signOut(){await draftChain;await releaseWakeLock();await auth.signOut();store=null;sync=null;draft=null;profile=null;sessionScope=null;renderWelcome();}
function shell(content){return h('div',{},demo?h('div',{class:'preview-banner'},'PREVIEW · separate from your live account'):null,h('div',{class:'shell'},h('header',{class:'topbar'},brand(),h('div',{class:'top-actions'},button([h('span',{class:'status-dot'}),demo?'Preview':'Saved here'],showSyncInfo,'pill',{id:'sync-status','aria-label':'Save and sync status'}),button(profile.name.slice(0,1).toUpperCase(),()=>{if(draft)confirm('Switch profile?','This workout will stay saved on this iPhone. You can resume it when you come back.','Switch profile',async()=>{await draftChain;draft=null;renderProfiles();});else renderProfiles();},`avatar ${profile.tone==='rose'?'rose':''}`,{'aria-label':'Switch profile'}),button(icon('settings'),()=>{view='settings';render();},'icon-button',{'aria-label':'Settings'}))),registration?.waiting?h('div',{class:'note update-note'},row(h('span',{},'A new version is ready.'),button('Update',guard(applyUpdate),'text-button'))):null,content),h('nav',{class:'bottom-nav','aria-label':'Main navigation'},[['today','home','Today'],['program','program','Program'],['progress','progress','Progress'],['history','log','Log']].map(([id,name,label])=>button([icon(name),h('span',{},label)],()=>{view=id;render();},`nav-item ${view===id?'active':''}`,{'aria-current':view===id?'page':null,'aria-label':label}))));}
function render(){if(!profile)return renderProfiles();if(draft&&view==='workout'){renderWorkout();return;}const content=view==='program'?renderProgram():view==='progress'?renderProgress():view==='history'?renderHistory():view==='settings'?renderSettings():renderToday();root.replaceChildren(shell(content));updateSyncStatus();}
function heading(kicker,title,sub){return h('header',{class:'page-heading'},h('p',{class:'eyebrow muted'},kicker),h('h1',{},title),h('p',{},sub));}
function exercises(type,week){const block=blockForWeek(PROGRAM,week);return (block.days[type]||[]).map((ex,i)=>({...ex,...settings.overrides?.[`${block.block}:${type}:${i}`],loadMode:settings.overrides?.[`${block.block}:${type}:${i}`]?.loadMode||(ex.n.includes('DB')?'per-hand':/Weighted|Pullup|Push Up|Leg Raise|Dead Bug|Nordic|Glute-Ham/.test(ex.n)?'added':'total')}));}
function nextTrainingDay(from){let date=from;for(let i=0;i<7;i++){if(DAY_TYPE[parseDay(date).getDay()]!=='rest')return date;date=addDays(date,1);}return from;}
function doneOn(day,type){return logs.some(l=>(l.scheduledDay||l.date)===day&&l.dayType===type&&l.sets?.length);}
function renderToday(){
 const weekStart=monday(selectedDay),week=programWeek(settings.startDate,selectedDay),type=DAY_TYPE[parseDay(selectedDay).getDay()],isRest=type==='rest',nextDay=isRest?nextTrainingDay(addDays(selectedDay,1)):selectedDay,nextType=DAY_TYPE[parseDay(nextDay).getDay()],nextWeek=programWeek(settings.startDate,nextDay),list=exercises(nextType,nextWeek),finished=doneOn(selectedDay,type),thisWeek=logs.filter(l=>l.date>=monday()&&l.date<=addDays(monday(),6));
 const content=h('div',{},heading(formatDate(localDay(),{weekday:'long',month:'long',day:'numeric'}),`Hey, ${profile.name}.`,'Show up. Put in the work. See it add up.'),row(h('p',{class:'eyebrow muted'},`WEEK ${week} / 12`),button([icon('program'),h('span',{},'Change week')],()=>{view='program';selectedWeek=week;render();},'pill')),
 h('div',{class:'week-strip'},Array.from({length:7},(_,i)=>{const date=addDays(weekStart,i),t=DAY_TYPE[parseDay(date).getDay()];return button([h('span',{},DAY_LABELS[parseDay(date).getDay()]),h('strong',{},parseDay(date).getDate()),h('span',{class:`day-mark ${doneOn(date,t)?'done':t!=='rest'?'training':''}`})],()=>{selectedDay=date;render();},`day-button ${date===selectedDay?'selected':''}`,{'aria-label':`${formatDate(date,{weekday:'long',month:'short',day:'numeric'})}, ${TYPE_LABELS[t]}`,'aria-pressed':date===selectedDay});})),
 draft?h('section',{class:'card resume-card'},row(h('div',{},h('p',{class:'eyebrow accent'},'SAVED WORKOUT'),h('h3',{},TYPE_LABELS[draft.dayType])),h('span',{class:'pill'},`${completedSets(draft).length} sets logged`)),h('p',{class:'tiny muted'},'Pick up exactly where you left off.'),button(['Resume workout',icon('arrow')],()=>{view='workout';render();requestWakeLock();})):null,
 h('section',{class:`hero ${isRest?'rest':''}`},h('div',{class:'hero-number','aria-hidden':'true'},String(['upper','lower','push','pull','legs'].indexOf(nextType)+1).padStart(2,'0')),h('p',{class:'eyebrow'},isRest?'RECOVERY DAY':finished?'SESSION COMPLETE':'YOUR SESSION'),h('h2',{},isRest?['Recover.',h('br'),'Come back strong.']:TYPE_LABELS[type]+'.'),h('p',{},isRest?`Next: ${TYPE_LABELS[nextType]} · ${formatDate(nextDay,{weekday:'long',month:'short',day:'numeric'})}`:`${list.length} exercises · ${buildSteps(list).length} planned sets · ${blockForWeek(PROGRAM,week).block}`),button([isRest?'Preview next workout':finished?'View workout':'Start workout',icon('arrow')],guard(async()=>{if(isRest){view='program';selectedWeek=nextWeek;expandedDay=nextType;render();}else if(finished){showLog(logs.find(l=>(l.scheduledDay||l.date)===selectedDay&&l.dayType===type));}else await startWorkout(type,week,selectedDay);}))),
 h('div',{class:'stats'},stat('THIS WEEK',thisWeek.length,'sessions'),stat('VOLUME',Math.round(thisWeek.reduce((s,l)=>s+workoutVolume(l),0)).toLocaleString(),'lb')),
 h('div',{class:'section-link'},h('h3',{},isRest?'Up next':'The lineup'),button('See all',()=>{view='program';selectedWeek=nextWeek;expandedDay=nextType;render();},'text-button')),
 h('div',{class:'card'},list.slice(0,3).map((ex,i)=>exerciseLine(ex,i))),h('p',{class:'tiny muted section-title'},'Essentials · Upper / Lower / Push / Pull / Legs'));
 return content;
}
function stat(label,value,unit){return h('div',{class:'card stat'},h('p',{class:'eyebrow muted'},label),h('div',{class:'value'},value,h('span',{class:'unit'},unit)));}
function exerciseLine(ex,index,edit){return h('div',{class:'exercise-line'},h('span',{class:'exercise-number'},String(index+1).padStart(2,'0')),h('div',{class:'grow'},h('h3',{},ex.n),h('p',{},`${ex.sets} × ${ex.reps}${ex.bo?` + ${ex.bo.sets} backoff`:''}${ex.drop?' · drop set':''}${ex.ss?' · superset':''}`)),edit?button('Edit',edit,'text-button',{'aria-label':`Edit ${ex.n}`}):h('span',{class:'tiny muted'},ex.tag));}
function renderProgram(){const block=blockForWeek(PROGRAM,selectedWeek),cycle=Math.floor(Math.max(0,(Date.parse(localDay())-Date.parse(settings.startDate))/86400000)/84),weekStart=addDays(settings.startDate,cycle*84+(selectedWeek-1)*7);return h('div',{},heading('THE ESSENTIALS','Your program.','Five training days. Three blocks. Twelve weeks.'),h('div',{class:'week-select','aria-label':'Program week'},Array.from({length:12},(_,i)=>button(String(i+1),()=>{selectedWeek=i+1;render();},`${selectedWeek===i+1?'active':''}`,{'aria-label':`Week ${i+1}`,'aria-pressed':selectedWeek===i+1}))),row(h('p',{class:'eyebrow accent'},`${block.block} · WEEK ${selectedWeek}`),h('span',{class:'tiny muted'},formatDate(weekStart))),h('div',{class:'divider'}),['upper','lower','rest','push','pull','legs','rest'].map((type,i)=>{
 const day=addDays(weekStart,i),list=exercises(type,selectedWeek),open=expandedDay===type&&type!=='rest';return h('section',{class:'card day-card'},button(row(h('div',{},h('p',{class:'eyebrow muted'},`${DAY_LABELS[parseDay(day).getDay()]} · ${formatDate(day)}`),h('div',{class:'day-name'},TYPE_LABELS[type])),type==='rest'?h('span',{class:'pill'},'Rest'):h('span',{class:'pill'},doneOn(day,type)?'Done':`${list.length} exercises`)),()=>{if(type==='rest')return;expandedDay=open?null:type;render();},'',{'aria-expanded':type==='rest'?null:open}),open?h('div',{class:'exercise-details'},list.map((ex,index)=>exerciseLine(ex,index,()=>editExercise(type,index,ex))),button(['Start this session',icon('arrow')],guard(()=>startWorkout(type,selectedWeek,day)),'primary start-small')):null);
 }),h('div',{class:'note'},'Use weights that match your effort today. Your previous sets are a reference, and each exercise keeps its own history.'));}
function editExercise(type,index,ex){const name=h('input',{value:ex.n,maxlength:100,'aria-label':'Exercise name'}),mode=h('select',{'aria-label':'How weight is recorded'},[['total','Total / machine stack'],['per-hand','Per dumbbell / hand'],['added','Added weight (0 = bodyweight)']].map(([v,t])=>h('option',{value:v,selected:ex.loadMode===v},t)));openModal('Make it yours.',h('div',{class:'stack'},h('p',{},'Swap an exercise for your equipment. Sets and rep targets stay the same. Its history will follow the exercise name.'),h('div',{class:'field'},h('label',{},'Exercise'),name),h('div',{class:'field'},h('label',{},'Weight convention'),mode)),[button('Save exercise',guard(async()=>{if(!name.value.trim())throw Error('Enter an exercise name.');settings.overrides={...settings.overrides,[`${blockForWeek(PROGRAM,selectedWeek).block}:${type}:${index}`]:{n:name.value.trim(),loadMode:mode.value}};await saveSettings();closeModal();render();})),button('Cancel',closeModal,'secondary')]);}
async function saveSettings(){await store.put(`settings:${profile.id}`,'settings',profile.id,settings);queueSync();}

function renderHistory(){return h('div',{},heading('THE WORK YOU PUT IN','Your log.',`${logs.length} saved ${logs.length===1?'session':'sessions'} · ${profile.name}`),logs.length?[...logs].sort((a,b)=>b.startedAt-a.startedAt).map(log=>button([row(h('span',{class:'eyebrow muted'},formatDate(log.date,{weekday:'short',month:'short',day:'numeric'})),h('span',{class:'badge'},`WEEK ${log.week}`)),h('h3',{},TYPE_LABELS[log.dayType]||'Workout'),h('div',{class:'meta'},h('span',{},`${log.sets.length} sets`),h('span',{},`${Math.round(workoutVolume(log)).toLocaleString()} lb volume`),h('span',{},formatTime(log.durationSecs)))],()=>showLog(log),'card history-entry')):h('div',{class:'empty'},icon('log'),h('h3',{},'Your first session starts the story.'),h('p',{},'Every completed set will be saved here. Start a workout from your plan.'),button('Open your program',()=>{view='program';render();})));}
function showLog(log){if(!log)return;const grouped=Map.groupBy?Map.groupBy(log.sets,s=>s.name):log.sets.reduce((map,s)=>{map.set(s.name,[...(map.get(s.name)||[]),s]);return map;},new Map());openModal(TYPE_LABELS[log.dayType]||'Workout',h('div',{class:'stack'},h('p',{},`${formatDate(log.date,{weekday:'long',month:'long',day:'numeric'})} · ${formatTime(log.durationSecs)}`),[...grouped].map(([name,sets])=>h('div',{},h('h3',{},name),sets.map(s=>h('div',{class:'set-history-row'},h('span',{class:'badge'},s.type),h('span',{class:'grow'},`${s.weight} lb × ${s.reps}${s.loadMode==='per-hand'?' / hand':s.loadMode==='added'?' added':''}`),s.rpe?h('span',{class:'tiny muted'},`RPE ${s.rpe}`):null)))),log.note?h('div',{class:'note'},log.note):null),[button('Close',closeModal),button('Remove workout',()=>{closeModal();openModal('Remove this workout?',h('p',{},'It will be removed from your log. You can restore it from Recently removed in Settings.'),[button('Remove workout',guard(async()=>{await store.put(log.id,'workout',profile.id,{...log},{deleted:true});closeModal();await refreshData();render();queueSync();toast('Workout moved to Recently removed.');}),'danger'),button('Cancel',closeModal,'secondary')]);},'text-button')]);}
function renderProgress(){const names=[...new Set(logs.flatMap(l=>l.sets.map(s=>s.name)))];return h('div',{},heading('SMALL WINS ADD UP','Your progress.','One point per session. One exercise at a time.'),names.length?names.map(name=>{const {points,bestWeight}=summarizeExercise(logs,name);if(!points.length)return null;const latest=points.at(-1);return h('section',{class:'card progress-card'},row(h('h3',{},name),h('div',{class:'value'},`${bestWeight}`,h('span',{class:'tiny muted'},' lb best'))),h('p',{class:'tiny muted'},`Latest: ${latest.weight} lb · ${points.length} ${points.length===1?'session':'sessions'}`),chart(points),h('div',{class:'chart-labels'},h('span',{},formatDate(points[0].date)),h('span',{},formatDate(latest.date))));}):h('div',{class:'empty'},icon('progress'),h('h3',{},'Progress starts with a first set.'),h('p',{},'Log a workout to start tracking the weights you use for each exercise.')));}
function chart(points){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('chart');svg.setAttribute('viewBox','0 0 320 94');svg.setAttribute('role','img');svg.setAttribute('aria-label',`Session weights: ${points.map(p=>`${formatDate(p.date)} ${p.weight} pounds`).join(', ')}`);const min=Math.min(...points.map(p=>p.weight)),max=Math.max(...points.map(p=>p.weight)),dateMin=Math.min(...points.map(p=>Date.parse(p.date))),dateMax=Math.max(...points.map(p=>Date.parse(p.date)));const positions=points.map((p,i)=>[points.length===1?160:dateMax>dateMin?8+(Date.parse(p.date)-dateMin)/(dateMax-dateMin)*304:8+i/Math.max(1,points.length-1)*304,76-(p.weight-min)/Math.max(5,max-min)*58]);const line=document.createElementNS(svg.namespaceURI,'polyline');line.setAttribute('points',positions.map(p=>p.join(',')).join(' '));svg.append(line);for(const [x,y] of positions){const circle=document.createElementNS(svg.namespaceURI,'circle');circle.setAttribute('cx',x);circle.setAttribute('cy',y);circle.setAttribute('r',3.5);svg.append(circle);}return svg;}
function renderSettings(){const date=h('input',{type:'date',value:settings.startDate,'aria-label':'Week one start date',onchange:guard(async e=>{if(!e.target.value)return;settings.startDate=monday(e.target.value);await saveSettings();toast('Week 1 start updated.');render();})}),increment=h('select',{'aria-label':'Weight increase',onchange:guard(async e=>{settings.increment=+e.target.value;await saveSettings();})},[2.5,5,10].map(v=>h('option',{value:v,selected:settings.increment===v},`${v} lb`)));const content=h('div',{},heading('MAKE IT YOURS','Settings.',`${profile.name} · Essentials 5× per week`),h('div',{class:'stack'},h('section',{class:'card'},h('p',{class:'eyebrow accent'},'YOUR TRAINING'),h('div',{class:'settings-row'},h('div',{},h('h3',{},'Week 1 starts'),h('p',{},'Aligned to Monday for the 5-day split.')),date),h('div',{class:'settings-row'},h('div',{},h('h3',{},'Progression step'),h('p',{},'Suggested after all working sets reach the top reps.')),increment),h('div',{class:'settings-row'},h('div',{},h('h3',{},'Timer sound'),h('p',{},'A gentle cue while the app is open.')),h('input',{type:'checkbox',checked:settings.sound,'aria-label':'Timer sound',onchange:guard(async e=>{settings.sound=e.target.checked;await saveSettings();})}))),h('section',{class:'card'},row(h('h3',{},'Saved on this device'),icon('check')),h('p',{id:'sync-detail',class:'tiny muted section-title'},demo?'Preview data is separate.':sync?.message||'Your workouts save locally first.'),button('Sync now',guard(async()=>{if(sync){await sync.run();await refreshData();render();}else toast('Preview mode does not sync.');}),'secondary'),!demo?button('Sign in again',()=>renderWelcome(),'text-button'):null,button('Review sync conflicts',guard(showConflicts),'text-button')),h('section',{class:'card'},h('h3',{},'Your data'),button('Export this profile',guard(exportProfile),'text-button'),button('Import workouts',showImport,'text-button'),button('Recently removed',guard(showRemoved),'text-button')),h('section',{class:'card'},h('h3',{},'On your Home Screen'),h('p',{class:'tiny muted section-title'},'Open LiftPlan in Safari, tap Share, then Add to Home Screen. Once installed, reopen it from the new icon.'),h('p',{class:'tiny muted'},'After the first load, the app and your saved workouts are available offline. Your timer resumes from real elapsed time when you return.')),h('div',{class:'note'},'The 5-day schedule comes from your original LiftPlan. The supplied 3-day Essentials PDF was used to review general training guidance. No RPE targets were invented for the 5-day exercises.'),h('p',{class:'tiny muted center'},`LiftPlan ${CONFIG.version} · Built for your next session`),!demo?button('Sign out',guard(signOut),'secondary'):null));return content;}
async function showConflicts(){const conflicts=await store.all('conflicts');if(!conflicts.length){openModal('Everything is clear.',h('p',{},'There are no conflicting changes to review.'),[button('Close',closeModal)]);return;}const conflict=conflicts[0];openModal('Two saved versions.',h('div',{class:'stack'},h('p',{},'This record was also changed on another device. Both versions have been kept until you choose.'),h('div',{class:'note'},`Record: ${conflict.local.payload?.name||TYPE_LABELS[conflict.local.payload?.dayType]||'Training settings'}`),h('p',{class:'tiny'},'Keeping this device’s change replaces the cloud version of this record. Using the cloud version discards this pending change only.')), [button('Keep this device’s change',guard(async()=>{await store.resolve(conflict.id,true);closeModal();await refreshData();render();queueSync();})),button('Use cloud version',guard(async()=>{await store.resolve(conflict.id,false);closeModal();await refreshData();render();queueSync();}),'secondary')]);}
async function showRemoved(){const removed=(await store.all('records')).filter(r=>r.kind==='workout'&&r.profile_id===profile.id&&r.deleted);openModal('Recently removed',removed.length?h('div',{class:'stack'},removed.map(record=>h('div',{class:'settings-row'},h('div',{},h('h3',{},TYPE_LABELS[record.payload.dayType]),h('p',{},formatDate(record.payload.date))),button('Restore',guard(async()=>{await store.put(record.id,'workout',profile.id,record.payload);closeModal();await refreshData();render();queueSync();toast('Workout restored.');}),'text-button')))):h('p',{},'No removed workouts.'),[button('Close',closeModal)]);}
async function exportProfile(){await draftChain;const all=await store.export(),data={version:2,profile:{name:profile.name},exportedAt:all.exportedAt,records:all.records.filter(r=>r.profile_id===profile.id),drafts:all.drafts.filter(d=>d.profileId===profile.id)};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=h('a',{href:url,download:`liftplan-${profile.id}-${localDay()}.json`});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function showImport(){const input=h('input',{type:'file',accept:'application/json,.json','aria-label':'Workout backup file',onchange:guard(async e=>{const file=e.target.files[0];if(!file)return;if(file.size>10000000)throw Error('This backup is too large.');const data=JSON.parse(await file.text());if(data.version!==2||!Array.isArray(data.records))throw Error('Choose a LiftPlan v2 backup file.');const imported=data.records.filter(r=>r.kind==='workout'&&!r.deleted);if(!imported.length)throw Error('This file has no saved workouts.');for(const r of imported){const p=r.payload;if(!p||typeof p.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||!Array.isArray(p.sets)||p.sets.some(s=>typeof s.name!=='string'||!validSet(s.weight,s.reps))||!Number.isFinite(p.startedAt))throw Error('This backup contains invalid workout records.');}closeModal();openModal('Import these workouts?',h('p',{},`${imported.length} sessions will be copied into ${profile.name}’s profile. Existing workouts stay as they are.`),[button('Import workouts',guard(async()=>{for(const record of imported){const payload={...record.payload,profileId:profile.id};await store.put(`workout:${crypto.randomUUID()}`,'workout',profile.id,payload);}closeModal();await refreshData();render();queueSync();toast('Workouts imported.');})),button('Cancel',closeModal,'secondary')]);})});openModal('Restore a backup',h('div',{class:'stack'},h('p',{},'Choose a v2 workout export. You’ll review the import before anything is added.'),input),[button('Cancel',closeModal,'secondary')]);}

async function startWorkout(type,week,scheduledDay){
 if(draft){confirm('You have a saved workout.','Resume it, or finish it before starting another session for this profile.','Resume workout',async()=>{view='workout';render();await requestWakeLock();});return;}
 const list=exercises(type,week);draft={id:`workout:${crypto.randomUUID()}`,profileId:profile.id,dayType:type,week,scheduledDay,date:localDay(),startedAt:Date.now(),cursor:0,steps:buildSteps(list).map(s=>({...s,done:false,skipped:false,weightInput:'',repsInput:'',rpe:''})),warmupsDone:[],restUntil:null,note:''};await persistDraft();view='workout';render();await requestWakeLock();
}
function persistDraft(){if(!draft||!store)return draftChain;const snapshot=structuredClone(draft),target=store,pid=profile.id;saving=true;setAutosave('Saving…');draftChain=draftChain.catch(()=>{}).then(()=>target.saveDraft(pid,snapshot)).then(()=>{saving=false;setAutosave('Saved on this iPhone');}).catch(e=>{saving=false;setAutosave('Save failed · keep the app open');throw e;});return draftChain;}
function setAutosave(text){const label=$('draft-save');if(label)label.textContent=text;}
function stepSuggestion(step){return suggestion(logs,step,draft.steps,settings.increment||2.5);}
function ensureInputs(step){if(step.weightInput!=='')return;const previous=[...draft.steps.slice(0,draft.cursor)].reverse().find(s=>s.name===step.name&&s.type===step.type&&s.done);const suggested=stepSuggestion(step);if(previous&&step.type!=='drop')step.weightInput=String(previous.weight);else if(suggested)step.weightInput=String(suggested.weight);}
function weightConvention(mode){return mode==='per-hand'?'Weight of one dumbbell / hand.':mode==='added'?'Added weight only. Enter 0 for bodyweight.':'Total load or the number on your machine stack.';}
function warmupText(count){return count===1?'One easy set at roughly 60% of your planned working load.':count===2?'Two easy ramp-up sets at roughly 50% and 70% of your planned working load.':'Three easy ramp-up sets at roughly 45%, 65%, and 85% of your planned working load. Reduce reps as you ramp up.';}
function renderWorkout(){
 if(!draft){view='today';render();return;}
 if(draft.restUntil&&secondsLeft(draft.restUntil)===0)draft.restUntil=null;
 const complete=draft.cursor>=draft.steps.length,step=draft.steps[draft.cursor],done=completedSets(draft).length,total=draft.steps.length;
 const content=h('main',{class:'workout-shell'},h('header',{class:'topbar'},button('Pause',guard(async()=>{await persistDraft();await releaseWakeLock();view='today';render();}),'pill'),h('span',{class:'eyebrow muted'},`${TYPE_LABELS[draft.dayType]} · WEEK ${draft.week}`),h('span',{id:'elapsed',class:'tiny muted'},formatTime((Date.now()-draft.startedAt)/1000))),h('div',{class:'workout-top'},row(h('span',{class:'tiny muted'},`${done} / ${total} sets logged`),h('span',{class:'autosave'},icon('check'),h('span',{id:'draft-save'},saving?'Saving…':'Saved on this iPhone'))),h('div',{class:'progress-track'},h('span',{}))));
 // Width uses a CSS custom property set below, rather than inline styles under the CSP.
 const progress=content.querySelector('.progress-track span');progress.style.width=`${done/total*100}%`;
 if(complete){content.append(renderCompletion(false));root.replaceChildren(content);return;}
 if(draft.restUntil){content.append(h('section',{class:'card rest-card'},h('p',{class:'eyebrow muted'},'TAKE A BREATHER'),h('div',{class:'timer',id:'rest-time',role:'timer'},formatTime(secondsLeft(draft.restUntil))),h('p',{},`Up next: ${step.name} · ${step.type==='backoff'?'backoff':step.type==='drop'?'drop set':`set ${step.round}`}`),button('I’m ready',guard(async()=>{draft.restUntil=null;await persistDraft();renderWorkout();})),h('div',{class:'row'},button('+30 seconds',guard(async()=>{draft.restUntil+=30000;await persistDraft();tick();}),'text-button'),button('End workout',showEndWorkout,'text-button'))));root.replaceChildren(content);return;}
 ensureInputs(step);
 const suggested=stepSuggestion(step),weight=h('input',{id:'set-weight',type:'number',inputmode:'decimal',min:'0',max:'2000',step:'any',value:step.weightInput,placeholder:'0','aria-label':'Weight in pounds',oninput:e=>{step.weightInput=e.target.value;persistDraft().catch(e=>toast(errorMessage(e)));}}),reps=h('input',{id:'set-reps',type:'number',inputmode:'numeric',min:'1',max:'200',step:'1',value:step.repsInput,placeholder:'0','aria-label':'Repetitions',oninput:e=>{step.repsInput=e.target.value;persistDraft().catch(e=>toast(errorMessage(e)));}});
 const effort=h('select',{id:'set-effort','aria-label':'Set effort RPE',onchange:e=>{step.rpe=e.target.value;persistDraft().catch(e=>toast(errorMessage(e)));}},[['','Optional'],['7','7 · 3 left'],['8','8 · 2 left'],['9','9 · 1 left'],['10','10 · max']].map(([value,text])=>h('option',{value,selected:step.rpe===value},text)));
 content.append(h('div',{},h('header',{class:'workout-heading'},h('p',{class:'set-tag'},`${step.type==='working'?'WORKING SET':step.type.toUpperCase()+' SET'} ${step.round}`),h('h1',{},step.name),h('div',{class:'row'},h('span',{class:'pill'},`${step.target}${step.target==='As many as possible'?'':' reps'}`),h('span',{class:'pill'},step.rest?`${formatTime(step.rest)} rest`:'No rest'),step.superset?h('span',{class:'pill'},'Superset'):null)),step.note?h('p',{class:'note section-title'},step.note):null,step.warmups&&!draft.warmupsDone.includes(step.exerciseIndex)?h('aside',{class:'warmup-card'},h('h3',{},`${step.warmups} warmup ${step.warmups===1?'set':'sets'} first`),h('p',{},warmupText(step.warmups)),button('Warmups done',guard(async()=>{draft.warmupsDone.push(step.exerciseIndex);await persistDraft();renderWorkout();}),'text-button')):null,h('p',{class:'load-note'},weightConvention(step.loadMode)),h('div',{class:'set-inputs'},h('div',{class:'field'},h('label',{for:'set-weight'},'WEIGHT · LB'),weight),h('div',{class:'field'},h('label',{for:'set-reps'},'REPS'),reps)),h('div',{class:'nudge-row'},[-5,-2.5,2.5,5].map(delta=>button(`${delta>0?'+':''}${delta}`,guard(async()=>{step.weightInput=String(Math.max(0,(Number(step.weightInput)||0)+delta));weight.value=step.weightInput;await persistDraft();})))),suggested?h('div',{class:'suggestion'},h('strong',{},`${suggested.weight} lb suggested. `),suggested.text):h('div',{class:'suggestion'},'First time logging this exercise. Choose your starting weight; we’ll remember it for next time.'),h('div',{class:'effort-row'},h('label',{for:'set-effort'},'How hard was the set?'),effort),h('p',{class:'form-error',id:'set-error',role:'alert'}),h('footer',{class:'workout-footer'},button([step.done?'Update set':'Log set',icon('check')],guard(logSet)),h('div',{class:'row'},button('Previous',guard(async()=>{if(draft.cursor>0){draft.cursor--;draft.restUntil=null;await persistDraft();renderWorkout();}}),'text-button',{disabled:draft.cursor===0}),button('Skip this set',guard(async()=>{step.skipped=true;step.done=false;draft.cursor++;await persistDraft();renderWorkout();}),'text-button'),button('End',showEndWorkout,'text-button'))),renderSessionSets()));root.replaceChildren(content);
}
function renderSessionSets(){return h('details',{class:'session-sets'},h('summary',{},'Review this session'),draft.steps.map((s,i)=>h('div',{class:'set-history-row'},h('span',{class:'grow'},s.name,h('span',{class:'tiny muted'},` · ${s.type}`)),h('span',{},s.done?`${s.weight} × ${s.reps}`:s.skipped?'Skipped':'—'),button('Edit',guard(async()=>{draft.cursor=i;draft.restUntil=null;await persistDraft();renderWorkout();}),'text-button',{'aria-label':`Edit ${s.name}, ${s.type} set ${s.round}`}))));}
async function logSet(){const step=draft.steps[draft.cursor],weight=step.weightInput===''?NaN:Number(step.weightInput),reps=step.repsInput===''?NaN:Number(step.repsInput);if(!validSet(weight,reps)){$('set-error').textContent='Enter a weight of 0 or more and whole reps from 1 to 200.';return;}step.weight=weight;step.reps=reps;step.done=true;step.skipped=false;draft.cursor++;draft.restUntil=step.rest>0&&draft.cursor<draft.steps.length?Date.now()+step.rest*1000:null;await persistDraft();renderWorkout();}
function showEndWorkout(){const count=completedSets(draft).length;openModal('Finish for today?',h('p',{},count?`${count} logged sets will be saved to your history. Unfinished sets will stay out of your totals.`:'No sets have been logged. You can keep this workout paused or discard the empty session.'),[button(count?'Save completed sets':'Discard empty session',guard(async()=>{closeModal();if(count)await finishWorkout();else{await draftChain;await store.deleteDraft(profile.id);draft=null;view='today';await releaseWakeLock();render();}})),button('Pause and come back',guard(async()=>{await persistDraft();closeModal();view='today';await releaseWakeLock();render();}),'secondary'),button('Keep training',closeModal,'text-button')]);}
function renderCompletion(saved,log=null){const sets=saved?log.sets:completedSets(draft),duration=saved?log.durationSecs:Math.floor((Date.now()-draft.startedAt)/1000);return h('section',{class:'completion'},h('div',{class:'finish-icon'},icon('check')),h('p',{class:'eyebrow accent'},saved?'SESSION SAVED':'SESSION WRAPPED'),h('h1',{},saved?['That’s work',h('br'),'in the bank.']:sets.length?'You put in the work.':'Ready when you are.'),h('p',{class:'muted'},saved?'Your session is saved on this iPhone. Cloud status appears on your home screen.':`${sets.length} sets logged. ${draft.steps.filter(s=>s.skipped).length} skipped. Review your sets or finish this session.`),h('div',{class:'stats'},stat('LOGGED',sets.length,'sets'),stat('TIME',formatTime(duration),'')),saved?button('Back to today',()=>{view='today';render();}):h('div',{class:'stack'},button('Save workout',guard(finishWorkout), 'primary',{disabled:!sets.length}),button('Review sets',guard(async()=>{draft.cursor=0;await persistDraft();renderWorkout();}),'secondary'),!sets.length?button('Pause or discard',showEndWorkout,'text-button'):null),!saved?renderSessionSets():null);}
async function finishWorkout(){await draftChain;const sets=completedSets(draft);if(!sets.length)throw Error('Log at least one set before saving.');const log={profileId:profile.id,dayType:draft.dayType,week:draft.week,scheduledDay:draft.scheduledDay,date:draft.date,startedAt:draft.startedAt,durationSecs:Math.floor((Date.now()-draft.startedAt)/1000),sets,note:draft.note||''};await store.put(draft.id,'workout',profile.id,log,{finishDraft:profile.id});draft=null;await releaseWakeLock();await refreshData();view='saved';root.replaceChildren(h('main',{class:'workout-shell'},renderCompletion(true,log)));queueSync();}
let audioContext;function playCue(){if(!settings.sound)return;try{audioContext||=new (window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.connect(gain);gain.connect(audioContext.destination);gain.gain.value=.035;oscillator.frequency.value=660;oscillator.start();oscillator.stop(audioContext.currentTime+.18);}catch{}}
async function requestWakeLock(){if('wakeLock' in navigator&&document.visibilityState==='visible'){try{wakeLock=await navigator.wakeLock.request('screen');}catch{}}}
async function releaseWakeLock(){try{await wakeLock?.release();}catch{}wakeLock=null;}
function tick(){if(!draft)return;const elapsed=$('elapsed');if(elapsed)elapsed.textContent=formatTime((Date.now()-draft.startedAt)/1000);if(!draft.restUntil)return;const left=secondsLeft(draft.restUntil),timer=$('rest-time');if(timer)timer.textContent=formatTime(left);if(!left){draft.restUntil=null;persistDraft().catch(e=>toast(errorMessage(e)));if(document.visibilityState==='visible')playCue();if(view==='workout')renderWorkout();}}
setInterval(tick,500);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){if(draft)persistDraft().catch(()=>{});releaseWakeLock();}else{tick();if(draft&&view==='workout')requestWakeLock();if(sync)queueSync();}});
window.addEventListener('online',()=>queueSync());window.addEventListener('offline',()=>{if(sync){sync.state='offline';sync.message='Saved on this iPhone · syncs when online';updateSyncStatus();}});
window.addEventListener('storage',event=>{if(event.key==='liftplan.v2.session'&&!auth.session()&&!demo){releaseWakeLock();if(draft)persistDraft().catch(()=>{});renderWelcome();}});
channel?.addEventListener('message',async e=>{if(e.data.scope!==sessionScope||draft||view==='saved')return;await refreshData();if(profile)render();});
setInterval(()=>{if(sync&&document.visibilityState==='visible')queueSync();},45000);
async function setupPwa(){if(!('serviceWorker' in navigator))return;try{registration=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});registration.addEventListener('updatefound',()=>{const next=registration.installing;next?.addEventListener('statechange',()=>{if(next.state==='installed'&&navigator.serviceWorker.controller){toast('A new version is ready.');if(profile&&view!=='workout')render();}});});const hadController=!!navigator.serviceWorker.controller;let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing||!hadController)return;refreshing=true;if(navigator.serviceWorker.controller)location.reload();});}catch{toast('Offline setup needs a connection. Your workouts still save locally.');}}
async function applyUpdate(){await draftChain;registration?.waiting?.postMessage({type:'ACTIVATE_UPDATE'});}
async function init(){try{await setupPwa();const session=auth.session();if(demo)await initializeScope('preview');else if(session?.user?.id)await initializeScope(session.user.id);else renderWelcome();navigator.storage?.persist?.().catch(()=>{});}catch(e){bootError(e);}}
init();
