export const PROGRAM=[
  {block:'Block 1',weeks:[1,2,3,4],days:{
    upper:[
      {n:'Flat DB Press',tag:'chest',sets:1,reps:'4-6',heavy:true,bo:{sets:1,reps:'8-10'},wu:3,rest:180,note:'Heavy compound. Full ROM, control the negative.'},
      {n:'2-Grip Lat Pulldown',tag:'back',sets:2,reps:'10-12',wu:2,rest:120},
      {n:'Seated DB Shoulder Press',tag:'shoulders',sets:2,reps:'12-15',wu:1,rest:120},
      {n:'Seated Cable Row',tag:'back',sets:2,reps:'10-12',drop:true,wu:1,rest:120,note:'Last set: drop ~50%, keep going.'},
      {n:'EZ Bar Skull Crusher',tag:'triceps',sets:2,reps:'12-15',wu:1,rest:0,ss:'EZ Bar Curl'},
      {n:'EZ Bar Curl',tag:'biceps',sets:2,reps:'12-15',rest:90},
    ],
    lower:[
      {n:'Hack Squat',tag:'quads',sets:1,reps:'4-6',heavy:true,bo:{sets:1,reps:'8-10'},wu:3,rest:180,note:'Heavy. Track weight week to week.'},
      {n:'Seated Hamstring Curl',tag:'hamstrings',sets:2,reps:'10-12',drop:true,wu:1,rest:120},
      {n:'Standing Calf Raise',tag:'calves',sets:2,reps:'12-15',wu:1,rest:0,ss:'Hanging Leg Raise'},
      {n:'Hanging Leg Raise',tag:'core',sets:2,reps:'12-15',rest:90},
    ],
    push:[
      {n:'Machine Shoulder Press',tag:'shoulders',sets:2,reps:'10-12',wu:2,rest:120},
      {n:'Cable Chest Press',tag:'chest',sets:2,reps:'12-15',drop:true,wu:1,rest:120},
      {n:'Triceps Pressdown',tag:'triceps',sets:2,reps:'12-15',drop:true,wu:1,rest:90},
      {n:'Close-Grip Push Up',tag:'triceps',sets:1,reps:'Max',wu:1,rest:90,note:'Elbows tight, as many as possible.'},
      {n:'DB Lateral Raise',tag:'shoulders',sets:2,reps:'10-12',wu:1,rest:90},
    ],
    pull:[
      {n:'1-Arm Half-Kneeling Lat Pulldown',tag:'back',sets:1,reps:'10-12',wu:1,rest:90,note:'Focus on lat squeeze, elbow tucked in.'},
      {n:'Weighted Pullup',tag:'back',sets:2,reps:'6-8',wu:2,rest:180},
      {n:'Pendlay Row',tag:'back',sets:2,reps:'8-10',wu:1,rest:120},
      {n:'Bayesian Cable Curl',tag:'biceps',sets:2,reps:'12-15',drop:true,wu:1,rest:90},
      {n:'Rope Facepull',tag:'rear delts',sets:2,reps:'15-20',wu:1,rest:90},
    ],
    legs:[
      {n:'Romanian Deadlift',tag:'hamstrings',sets:2,reps:'10-12',wu:2,rest:120,note:'Neutral spine, hips back, deep hamstring stretch.'},
      {n:'Leg Press',tag:'quads',sets:3,reps:'8-10',wu:2,rest:120},
      {n:'Leg Extension',tag:'quads',sets:2,reps:'12-15',drop:true,wu:1,rest:90},
      {n:'Seated Calf Raise',tag:'calves',sets:2,reps:'15-20',wu:1,rest:0,ss:'Cable Crunch'},
      {n:'Cable Crunch',tag:'core',sets:2,reps:'12-15',rest:90},
    ],
  }},
  {block:'Block 2',weeks:[5,6,7,8],days:{
    upper:[
      {n:'2-Grip Pullup',tag:'back',sets:1,reps:'4-6',heavy:true,bo:{sets:1,reps:'6-8'},wu:3,rest:180,note:'Add belt weight. Start with weaker grip.'},
      {n:'Weighted Dip',tag:'chest',sets:1,reps:'4-6',heavy:true,bo:{sets:1,reps:'8-10'},wu:2,rest:180,note:'Full ROM, chest leans slightly forward.'},
      {n:'Incline CS DB Row',tag:'back',sets:2,reps:'10-12',wu:1,rest:120},
      {n:'Standing DB Arnold Press',tag:'shoulders',sets:2,reps:'12-15',wu:1,rest:120,note:'Palms in at bottom, rotate out as you press.'},
      {n:'DB Incline Curl',tag:'biceps',sets:2,reps:'12-15',wu:1,rest:0,ss:'DB French Press'},
      {n:'DB French Press',tag:'triceps',sets:2,reps:'12-15',rest:90},
    ],
    lower:[
      {n:'Single-Leg Leg Press',tag:'quads',sets:1,reps:'6-8/leg',heavy:true,bo:{sets:1,reps:'10-12/leg'},wu:3,rest:180,note:'Start with weaker leg. High wide foot placement.'},
      {n:'Glute-Ham Raise',tag:'hamstrings',sets:1,reps:'10-12',wu:1,rest:90,note:'Sub: Lying leg curl if no GHR machine.'},
      {n:'Roman Chair Crunch',tag:'core',sets:2,reps:'12-15',wu:1,rest:0,ss:'Seated Calf Raise'},
      {n:'Seated Calf Raise',tag:'calves',sets:2,reps:'12-15',rest:90},
    ],
    push:[
      {n:'Machine Chest Press',tag:'chest',sets:2,reps:'8-10',wu:2,rest:120,note:'Squeeze your chest.'},
      {n:'Seated DB Shoulder Press',tag:'shoulders',sets:3,reps:'10-12',wu:2,rest:120},
      {n:'Cable Triceps Kickback',tag:'triceps',sets:2,reps:'12-15',drop:true,wu:1,rest:90,note:'Lock elbow behind torso, lean slightly forward.'},
      {n:'Close-Grip Push Up',tag:'triceps',sets:1,reps:'Max',rest:90},
      {n:'Cable Lateral Raise',tag:'shoulders',sets:2,reps:'12-15',wu:1,rest:90,note:'Lean away from cable.'},
    ],
    pull:[
      {n:'1-Arm Half-Kneeling Lat Pulldown',tag:'back',sets:1,reps:'10-12',wu:1,rest:90},
      {n:'T-Bar Row',tag:'back',sets:2,reps:'10-12',wu:2,rest:120,note:'Squeeze shoulder blades, avoid shrugging.'},
      {n:'Lat Pulldown',tag:'back',sets:3,reps:'8-10',drop:true,wu:2,rest:120},
      {n:'Reverse Pec Deck',tag:'rear delts',sets:2,reps:'12-15',drop:true,wu:1,rest:90},
      {n:'Spider Curl',tag:'biceps',sets:2,reps:'12-15',drop:true,wu:1,rest:90},
    ],
    legs:[
      {n:'DB Bulgarian Split Squat',tag:'quads',sets:3,reps:'10-12',wu:2,rest:120,note:'Start with weaker leg. Squat deep.'},
      {n:'DB Romanian Deadlift',tag:'hamstrings',sets:3,reps:'10-12',wu:2,rest:120},
      {n:'Goblet Squat',tag:'quads',sets:3,reps:'12-15',wu:1,rest:90},
      {n:'Leg Press Toe Press',tag:'calves',sets:2,reps:'15-20',wu:1,rest:0,ss:'Machine Crunch'},
      {n:'Machine Crunch',tag:'core',sets:2,reps:'12-15',rest:90},
    ],
  }},
  {block:'Block 3',weeks:[9,10,11,12],days:{
    upper:[
      {n:'Machine Chest Press',tag:'chest',sets:1,reps:'4-6',heavy:true,bo:{sets:1,reps:'8-10'},wu:3,rest:180,note:'Heavy + backoff. Squeeze chest.'},
      {n:'Machine Pulldown',tag:'back',sets:2,reps:'10-12',drop:true,wu:2,rest:120,note:'Elbows down and in.'},
      {n:'Cable Shoulder Press',tag:'shoulders',sets:2,reps:'12-15',drop:true,wu:1,rest:120,note:'Cables at shoulder height, torso upright.'},
      {n:'Helms DB Row',tag:'back',sets:2,reps:'10-12',wu:1,rest:120,note:'Elbows out and back at 45°.'},
      {n:'Overhead Cable Triceps Extension',tag:'triceps',sets:2,reps:'12-15',wu:1,rest:0,ss:'Cable EZ Curl'},
      {n:'Cable EZ Curl',tag:'biceps',sets:2,reps:'12-15',rest:90},
    ],
    lower:[
      {n:'Machine Squat',tag:'quads',sets:1,reps:'4-6',heavy:true,bo:{sets:1,reps:'8-10'},wu:3,rest:180},
      {n:'Nordic Ham Curl',tag:'hamstrings',sets:1,reps:'8-10',wu:1,rest:90,note:'Sub: Lying Leg Curl if no Nordic bench.'},
      {n:'Seated Calf Raise',tag:'calves',sets:2,reps:'10-12',wu:1,rest:0,ss:'Dead Bug (2-Arm 2-Leg)'},
      {n:'Dead Bug (2-Arm 2-Leg)',tag:'core',sets:2,reps:'10-12',rest:90,note:'Slow, lower back flat throughout.'},
    ],
    push:[
      {n:'Standing DB Arnold Press',tag:'shoulders',sets:2,reps:'10-12',wu:2,rest:120},
      {n:'Cable Chest Press',tag:'chest',sets:2,reps:'10-12',drop:true,wu:2,rest:120},
      {n:'DB Triceps Kickback',tag:'triceps',sets:2,reps:'10-12',drop:true,wu:1,rest:90},
      {n:'Close-Grip Push Up',tag:'triceps',sets:1,reps:'Max',rest:90},
      {n:'Machine Lateral Raise',tag:'shoulders',sets:2,reps:'10-12',wu:1,rest:90},
    ],
    pull:[
      {n:'1-Arm Half-Kneeling Lat Pulldown',tag:'back',sets:1,reps:'10-12',wu:1,rest:90},
      {n:'Neutral-Grip Lat Pulldown',tag:'back',sets:3,reps:'8-10',drop:true,wu:2,rest:120},
      {n:'Meadows Row',tag:'back',sets:2,reps:'10-12',wu:2,rest:120,note:'Brace non-working hand on knee.'},
      {n:'Inverse Zottman Curl',tag:'biceps',sets:2,reps:'10-12',drop:true,wu:1,rest:90,note:'Hammer on concentric, supinated on eccentric.'},
      {n:'Bent-Over Reverse DB Flye',tag:'rear delts',sets:2,reps:'15-20',wu:1,rest:90},
    ],
    legs:[
      {n:'Romanian Deadlift',tag:'hamstrings',sets:2,reps:'10-12',wu:2,rest:120},
      {n:'DB Walking Lunge',tag:'quads',sets:3,reps:'8-10',wu:2,rest:120,note:'Medium strides, minimize rear-leg push.'},
      {n:'Leg Extension',tag:'quads',sets:1,reps:'12-15',drop:true,wu:1,rest:90},
      {n:'Standing Calf Raise',tag:'calves',sets:2,reps:'15-20',wu:1,rest:0,ss:'Plate-Weighted Crunch'},
      {n:'Plate-Weighted Crunch',tag:'core',sets:2,reps:'12-15',rest:90,note:'Hold plate to chest, crunch hard.'},
    ],
  }},
];
